language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

matrix:
    allow_failures:
        - php: 7.0

install:
    - composer install
script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs src --standard=PSR2
    # It's nice to have the MessDetector output in the build log, but don't fail because of it.
    - ./vendor/bin/phpmd src text ./phpmd.xml || true

sudo: false
